<?php

/**
 * Implements hook_permission().
 */
function worx_social_review_permission() {
  return array(
    'social review email' => array(
      'title' => t('Social Review Email'),
      'description' => t('Send social review emails'),
    )
  );
}

/**
 * implements hook_menu().
 */
function worx_social_review_menu() {
  $items['admin/config/worx_features/social'] = array(
    'title' => 'Social Links',
    'description' => 'Set initial links for Social Review',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('worx_social_review_settings_form'),
    'access arguments' => array('social review email'),
    'file' => 'worx_social_review.admin.inc',
    'file path' => drupal_get_path('module', 'worx_social_review'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/worx_features/social/general'] = array(
    'title' => 'General Settings',
    'description' => 'Set initial links for Social Review',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('worx_social_review_settings_form'),
    'access arguments' => array('social review email'),
    'file' => 'worx_social_review.admin.inc',
    'file path' => drupal_get_path('module', 'worx_social_review'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/social_review/email'] = array(
    'title' => 'Social Review Email',
    'description' => 'Send review links email',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('worx_social_review_email_form'),
    'access arguments' => array('social review email'),
    'file' => 'worx_social_review_email_form.inc',
    'file path' => drupal_get_path('module', 'worx_social_review'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/social_review/email/general'] = array(
    'title' => 'Social Review Email Form',
    'description' => 'Send review links email',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('worx_social_review_email_form'),
    'access arguments' => array('social review email'),
    'file' => 'worx_social_review_email_form.inc',
    'file path' => drupal_get_path('module', 'worx_social_review'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/social_review/email/template'] = array(
    'title' => 'Social Review Email Template',
    'description' => 'Adjust email template',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('worx_social_review_email_template_form'),
    'access arguments' => array('social review email'),
    'file' => 'worx_social_review_email_template_form.inc',
    'file path' => drupal_get_path('module', 'worx_social_review'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/social_review/email/bulk'] = array(
    'title' => 'Social Review Bulk Email',
    'description' => 'Queue up email address to bulk send on cron runs',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('worx_social_review_email_bulk_form'),
    'access arguments' => array('social review email'),
    'file' => 'worx_social_review_email_bulk_form.inc',
    'file path' => drupal_get_path('module', 'worx_social_review'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_cron().
 */
function worx_social_review_cron() {
  $i = 0;
  while ($i < 25) {
    $record = db_select('worx_social_review_queue', 'q')
      ->fields('q')
      ->range(0, 1);

    $results = $record->execute();

    while ($result = $results->fetchAssoc()) {
      $email = $result['email'];
      $rsid = $result['rsid'];

      $sent = worx_social_review_bulk_send($email);

      if ($sent) {
        db_delete('worx_social_review_queue')
          ->condition('rsid', $rsid, '=')
          ->execute();
      }
    }

    $i++;
  }
}

function worx_social_review_bulk_send($email) {
  $params = array();
  $body_var = variable_get('email_body', '');
  $params['body'] = $body_var['value'];
  $from = variable_get('worx_social_review_default_sender', '');
  $to = $email;
  $body = str_replace(
    $search = array(
      '[google]',
      '[yahoo]',
      '[bing]',
      '[yp]',
      '[foursquare]',
      '[urbanspoon]',
      '[ta]',
    ),
    $replace = array(
      variable_get('worx_social_review_google_link', 'Error: No link. Please contact site administrator.'),
      variable_get('worx_social_review_yahoo_link', 'Error: No link. Please contact site administrator.'),
      variable_get('worx_social_review_bing_link', 'Error: No link. Please contact site administrator.'),
      variable_get('worx_social_review_yp_link', 'Error: No link. Please contact site administrator.'),
      variable_get('worx_social_review_foursquare_link', 'Error: No link. Please contact site administrator.'),
      variable_get('worx_social_review_urban_spoon_link', 'Error: No link. Please contact site administrator.'),
      variable_get('worx_social_review_ta_link', 'Error: No link. Please contact site administrator.'),
    ),
    $subject = $params['body']
  );
  $subject = variable_get('worx_social_review_bulk_subject', '');
  $message = array(
    'key' => 'worx_social_review',
    'to' => $to,
    'from' => $from,
    'subject' => $subject,
    'body' => $body,
    'headers' => array(
      'From' => $from,
      'Sender' => $from,
      'Return-Path' => $from,
    ),
  );
  $dupe = $message;
  $message = mimemail_prepare_message($message);
  mimemail_mailengine('send', $message);
  $dupe['to'] = 'reviews@worxco.net';
  $dupe = mimemail_prepare_message($dupe);
  return mimemail_mailengine('send', $dupe);
}
